on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '**.md'
    - 'assets/**'
    - '.vscode/**'
    - '.devcontainer/**'
    - '.github/**'
jobs:
  scripts:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '6.0.x'
      - name: Run the build of the zip outputs in the local git folder BinaryDownloads
        run: .\publishtobinariesfolder.cmd D:\a\azure-sdk-for-sap-odata\azure-sdk-for-sap-odata\BinaryDownloads
        shell: cmd  

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add new binaries"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
